### PR TITLE
Streamline the Development Environment Setup.

### PR DESCRIPTION
**Pull request by JeffNeff**
I wanted to take a step forward in the "get a dev started quickly" direction. This PR includes several Makefile targets, as well as a few install scripts to quickly realize the prerequisites and/or deploy Triggermesh to a local Docker Desktop environment. 

The suggested process and commands can be found in the updated readme.

### CODE REVIEW

**Comment by JeffNeff** [comment]
@sebgoa  @jmcx should we kill this? seems no traction

**Comment by sebgoa** [comment]
@sameersbn Any chance you can look at this, I think it would be nice.

**Comment by sameersbn** [comment]
@sebgoa sure!

**Review by sameersbn — APPROVED** [review]

**Comment by tzununbekov** [comment]
What's the status of this? Can we close it?

**Comment by tzununbekov** [comment]
Closing as stale.

**Pull request closed without merging**
