### PR TITLE
Update azservicebus to 1.1.0

### LINKED ISSUE #1128: Issue with Azure Servicebus Topic & Queue Source
There is an issue with our sources azure servicebus topic and queue after updating the azservicebus library from 1.0.2 to 1.1.0 https://github.com/triggermesh/triggermesh/pull/1115.

The issue is related with the messages received, is always empty after the update.

### PR DESCRIPTION
**Pull request by FranBarrera**
Closes #1128

### CODE REVIEW

**Review by odacremolbap — APPROVED** [review]
Note to other reviewers if any: setting the AMQP field to nil still did not solve the issue, so the previous struct needed to be added to have the proper marhaling to JSON without breaking the CloudEvent body.

**Comment by tzununbekov** [comment]
FWIW, e2e tests are failing with an error that may point to the Azure thing again.

**Comment by odacremolbap** [comment]
Seems to be something related to the AzureActivityLogsSource, is it possible that it is using the updated Azure library also?
@FranBarrera ^^

**Comment by FranBarrera** [comment]
@tzununbekov @odacremolbap I just re-launch the e2e tests and it's working fine. We've always have some random issues with azure e2e tests and mostly related with AzureActivityLogsSource:
https://github.com/triggermesh/triggermesh/blob/main/test/e2e/sources/azureactivitylogs/main.go#L169-L172

**Pull request merged**
