### PR TITLE
feat: suport annotations in the adapter override spec

### LINKED ISSUE #1394: AdapterOverrides should support Annotations alongside Labels
Currently the spec for adapterOverrides only supports passing in Labels. Annotations should ideally also be supported.

### PR DESCRIPTION
**Pull request by knechtionscoding**
Allows support for Annotations in the adapterOverride spec

closes #1394

### CODE REVIEW

**Comment by knechtionscoding** [comment]
I didn't see any specific tests for these files (but I'm happy to add them if they are just structured differently).

**Comment by tzununbekov** [comment]
Hey @knechtionscoding, thanks for the contribution!
You need to update CRDs to make new attributes available in the components' specifications. We have a Python script to propagate these changes automatically, all you have to do is update `hack/crd-update/crd-update.py`:

```diff
diff --git a/hack/crd-update/crd-update.py b/hack/crd-update/crd-update.py
index 6f78d5a4..855dc14b 100755
--- a/hack/crd-update/crd-update.py
+++ b/hack/crd-update/crd-update.py
@@ -17,6 +17,11 @@ try:
           description: Kubernetes object parameters to apply on top of default adapter values.
           type: object
           properties:
+            annotations:
+              description: Adapter annotations.
+              type: object
+              additionalProperties:
+                type: string
             labels:
               description: Adapter labels.
               type: object
``` 

then run `./hack/crd-update/update-all-crds.sh` and commit all changes after the script finishes its job.

Regarding the tests. There is a totally outdated and inefficient [TestAdapterOverrideOptions](https://github.com/triggermesh/triggermesh/blob/v1.24.4/pkg/reconciler/base_test.go#L89-L94), and we need to make it relevant someday, meanwhile, the easy path is to add (Pod)Annotation objectOption in [deployment_test.go](https://github.com/triggermesh/triggermesh/blob/v1.24.4/pkg/reconciler/resource/deployment_test.go#L52-L74) and [knservice_test.go](https://github.com/triggermesh/triggermesh/blob/v1.24.4/pkg/reconciler/resource/knservice_test.go#L52-L72) to validate its effect on the adapter.

**Comment by knechtionscoding** [comment]
@tzununbekov I think I've got all of that done, let me know if there's anything left!

**Comment by tzununbekov** [comment]
Yes, perfect! I forgot about the codegen update, so I took care of it to get this PR merged today. Thanks!

**Review by tzununbekov — APPROVED** [review]

**Comment by knechtionscoding** [comment]
Appreciate the help to get it over the finish line @tzununbekov !

**Pull request merged**
