### PR TITLE
Bump ko version to v0.10.0

### PR DESCRIPTION
**Pull request by antoineco**

### CODE REVIEW

**Review by cab105 — APPROVED** [review]

**Comment by tzununbekov** [comment]
It looks like after this PR `ko resolve` step in our CI became very unstable

**Comment by antoineco** [comment]
@tzununbekov Indeed, the resource usage went over the roof.

I see three options:
1. Revert (drawback: this is buying us time but doesn't fix the problem)
2. Reduce `ko'`s build concurrency
3. Use larger worker nodes in CircleCI

Which one do you prefer?

**Comment by tzununbekov** [comment]
@antoineco depending on our CircleCI account credits usage I'd first try switching to the beefier node and if it doesn't help, adjust ko's concurrency

**Comment by antoineco** [comment]
@tzununbekov not an option:

image

I opened https://github.com/google/ko/issues/642 and I'm reverting this PR right now.

**Pull request merged**
