### PR TITLE
addresing the sqs validating time duration issue

### PR DESCRIPTION
**Pull request by AmanSarraf**
addressing Issue : https://github.com/triggermesh/triggermesh/issues/981

### CODE REVIEW

**Comment by AmanSarraf** [comment]
please do review @JeffNeff

**Review by JeffNeff — APPROVED** [review]
LGTM

**Comment by sebgoa** [comment]
@odacremolbap I doubt this does what you wanted

**Comment by odacremolbap** [comment]
This is fine, the `duration` validation is supported at [Kubernete's CRDs](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation-rules).

image

**Pull request merged**
