### PR TITLE
Rename GoogleCloudRepositoriesSource to GoogleCloudSourceRepositoriesSource 

### LINKED ISSUE #376: Rename `GoogleCloudRepositoriesSource` to `GoogleCloudSourceRepositoriesSource`
It's quite a mouthful, but the product is called **Cloud Source Repositories**: https://cloud.google.com/source-repositories

To do:
- Rename event types (maybe `com.google.cloud.sourcerepo.notification` to match the [REST API](https://cloud.google.com/source-repositories/docs/reference/rest))
- Rename relevant source files (CRD, API type/lifecycle, reconciler package, e2e test)
- Rename misc references (`pkg/apis/sources/register.go`, `pkg/sources/reconciler/testing/listers.go`)

### PR DESCRIPTION
**Pull request by JeffNeff**
Closes #376

### CODE REVIEW

**Review by antoineco — CHANGES_REQUESTED** [review]
Looking good! Only 1 comment:

We also need to perform the necessary renamings inside [test/e2e/sources/googlecloudrepositories/main.go](https://github.com/triggermesh/triggermesh/blob/1d8390e2bbe5fb30ec9dbe62fc2b8f67747a477c/test/e2e/sources/googlecloudrepositories/main.go) (including the directory name and package), otherwise E2E tests will fail on `main` after merging.

**Comment by JeffNeff** [comment]
@antoineco okay!

**Comment by JeffNeff** [comment]
@antoineco ... im now getting linter errors to unrelated files.. 

```
(base) jeffreynaef@Jeffreys-MacBook-Pro triggermesh % make lint
golangci-lint run --timeout 5m ./cmd/... ./pkg/apis/... ./pkg/function/... ./pkg/routing/... ./pkg/sources/... ./pkg/targets/... ./pkg/transformation/...
pkg/sources/adapter/azureeventhubsource/trace/trace.go:17:1: ST1000: at least one file in a package should have a package comment (stylecheck)
package trace
^
pkg/transformation/pipeline/transformer/store/store.go:17:1: ST1000: at least one file in a package should have a package comment (stylecheck)
package store
^
pkg/routing/eventfilter/filter.go:17:1: ST1000: at least one file in a package should have a package comment (stylecheck)
package eventfilter
^
make: *** [lint] Error 1
```

**Comment by antoineco** [comment]
@JeffNeff could you please try merging main again?

**Comment by antoineco** [comment]
@JeffNeff this doesn't look right, I see old code being pulled in this PR. The Git Reset command I shared should revert your code to a good state.

**Comment by JeffNeff** [comment]
When i use your command and push i get a merge conflict.. then if i try to merge main to fix the conflict it brings back, what i think is, the old code you are referring too :/

**Comment by antoineco** [comment]
@JeffNeff you need to **force push** (`git push --force`)

**Comment by antoineco** [comment]
@JeffNeff I fixed the conflict

**Review by antoineco — APPROVED** [review]

**Pull request merged**
