### PR TITLE
Add `crd-update` tool

### PR DESCRIPTION
**Pull request by antoineco**
An attempt at easing the process of propagating changes to `adapterOverrides` to all CRDs, as discussed in #847.

The Python tool takes a CRD file on stdin, outputs the updated version to stdout.

A batch script was also added for convenience, to run the Python tool on _all_ CRDs at once and update them on disk.

**Note:** The `ruamel.yaml` library changes the location of line breaks in `description` fields that contain long strings, such as URLs, because it seems pretty relaxed about the value of `yaml.width`. (I opened [this ticket](https://sourceforge.net/p/ruamel-yaml/tickets/427/))
It doesn't bother me personally, but I'm open to comments. I had to relax the YAMLlint rule for lines longer than 120 characters for that exact reason.

### CODE REVIEW

**Comment by tzununbekov** [comment]
Nice! Do you think this tool is worth mentioning somewhere in the contribution guide?

**Comment by antoineco** [comment]
Maybe, it's very specific to `adapterOverrides` so it depends whether we plan to add a lot more overrides in the future.

**Review by tzununbekov — APPROVED** [review]
Well, I looked at the contents of the `hack` directory and it seems that we're OK with not having documentation there. I hope we'll remember what is there and how to use it 🙂 
Leaving this up to you!

**Comment by antoineco** [comment]
I'll add a README to the hack directory with the list of available utilities and their purpose. You're right, we should do a better job at documenting these otherwise we'll forget what they were created for.

**Pull request merged**
