### PR TITLE
Update knative.dev dependencies to v0.26

### PR DESCRIPTION
**Pull request by antoineco**
Follow up to my last PR: #45

Now that we are using Knative v0.25 libs, do the next and final update to v0.26.

Notable changes:

- `controller.NewImplFull` is no longer available and was replaced with `NewContext`.
    - See https://github.com/knative/pkg/pull/2222
- `resolver.NewURIResolver` is no longer available and was replaced with `NewURIResolverFromTracker`.
    - See https://github.com/knative/pkg/pull/2228

---

`go get` update log:

```console
$ go get knative.dev/eventing@v0.26.0
go get: upgraded contrib.go.opencensus.io/exporter/prometheus v0.3.0 => v0.4.0
go get: upgraded github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e => v0.0.0-20210331224755-41bb18bfe9da
go get: upgraded github.com/prometheus/common v0.26.0 => v0.30.0
go get: upgraded github.com/prometheus/statsd_exporter v0.20.0 => v0.21.0
go get: upgraded go.uber.org/zap v1.18.1 => v1.19.0
go get: upgraded golang.org/x/crypto v0.0.0-20210513164829-c07d793c2f9a => v0.0.0-20210817164053-32db794688a5
go get: upgraded golang.org/x/net v0.0.0-20210805182204-aaa1db679c0d => v0.0.0-20210825183410-e898025ed96a
go get: upgraded k8s.io/api v0.20.7 => v0.21.4
go get: upgraded k8s.io/apiextensions-apiserver v0.20.7 => v0.21.4
go get: upgraded k8s.io/apimachinery v0.20.7 => v0.21.4
go get: upgraded k8s.io/code-generator v0.20.7 => v0.21.4
go get: upgraded k8s.io/klog/v2 v2.5.0 => v2.8.0
go get: upgraded k8s.io/kube-openapi v0.0.0-20210113233702-8566a335510f => v0.0.0-20210305001622-591a79e4bda7
go get: upgraded knative.dev/eventing v0.25.1 => v0.26.0
go get: upgraded knative.dev/pkg v0.0.0-20210902173607-844a6bc45596 => v0.0.0-20210919202233-5ae482141474
go get: upgraded sigs.k8s.io/structured-merge-diff/v4 v4.0.3 => v4.1.2
```

```console
$ go get knative.dev/serving@v0.26.0
go get: upgraded github.com/google/go-containerregistry v0.5.2-0.20210709161016-b448abac9a70 => v0.6.0
go get: upgraded knative.dev/networking v0.0.0-20210803181815-acdfd41c575c => v0.0.0-20210914225408-69ad45454096
go get: upgraded knative.dev/serving v0.25.1 => v0.26.0
```

```console
$ go get knative.dev/pkg@release-0.26
(no update)
```

### CODE REVIEW

**Review by odacremolbap — DISMISSED** [review]

**Comment by odacremolbap** [comment]
Sorry, approved not noticing that it was draft/didn't build.

**Comment by antoineco** [comment]
@odacremolbap I'm just fixing this Sink Resolver thinggy in the tests, and then we're good to go.

**Comment by antoineco** [comment]
Ready for review, but depends on #48.

**Review by odacremolbap — APPROVED** [review]
:shipit:

**Pull request merged**
