### PR TITLE
bug/concurrent-processing-of-transformations

### PR DESCRIPTION
**Pull request by nkreiger**
Moving the logic from the instantiation of the adapter scope, to the application, puts everything inside the CE http request scope and fixes the issue (as far as my testing can tell)...going to perform even more heavy duty testing on it to be sure...opening PR for suggestions / thoughts

issue:
https://github.com/triggermesh/triggermesh/issues/1133

### CODE REVIEW

**Comment by JeffNeff** [comment]
What was the bug or issue that was occurring?

**Comment by nkreiger** [comment]
> What was the bug or issue that was occurring?

sorry I messed up linking the issue to the PR

https://github.com/triggermesh/triggermesh/issues/1133

**Comment by JeffNeff** [comment]
got it! okay!

**Comment by tzununbekov** [comment]
@nkreiger thanks for the contribution 🙇‍♂️  By any chance, is it possible to add the test that would reproduce described race condition to make sure that we fixed it?
@sameersbn how can we employ [Circle CI issue](1131) fix in this branch to have tests running?

**Comment by sameersbn** [comment]
@tzununbekov there's something weird going on with circle ci when it comes to PR's submitted by @nkreiger . I've contacted the circleci support to try and sort it out.

**Comment by nkreiger** [comment]
@tzununbekov @sameersbn I'm a bit pressed for time, I could maybe get to writing a test sometime next week...unless @JeffNeff you were working on one?

its not overly complicated, just need to concurrently spam in a bash script the cloud events receiver, maybe write the outputs to a variable or file, and if all the ids don't match or their are duplicates, it means one overrode...

**Comment by sameersbn** [comment]
@nkreiger could you please resolve the conflicts ?

**Comment by JeffNeff** [comment]
I can  play with the tests, But I do not have cycles right now.. It will have to be next week.

**Comment by sameersbn** [comment]
@nkreiger gentle reminder to rebase the PR. Once done, i'll merge this one  for ya!

**Comment by nkreiger** [comment]
@sameersbn sorry about the delay, I mixed this message with another one that got merged, and didn't realize I hadn't rebased this. Let me know if you need anything else.

**Comment by sameersbn** [comment]
@nkreiger the webhook.go does not seem to be gofmt'd and it therefore failing the static tests.

**Comment by nkreiger** [comment]
@sameersbn sorry for the massive delay on this, got caught up. I tried to commit again to see if this passes, I  did `go fmt ./...` but nothing changed

**Comment by sameersbn** [comment]
thanks for resolving the linter issues. @tzununbekov @odacremolbap when you have the time, please take a look at these changes.

**Pull request merged**
