### PR TITLE
Use standard naming scheme across all CRDs

### PR DESCRIPTION
**Pull request by antoineco**
Part of #12.
Follow up to #81.

Rename CRD files to `<kind>.yaml` to follow a consistent naming scheme.

Result:

```console
$ ls -1 config/3*
300-awscloudwatchlogssource.yaml
300-awscloudwatchsource.yaml
300-awscodecommitsource.yaml
300-awscognitoidentitysource.yaml
300-awscognitouserpoolsource.yaml
300-awsdynamodbsource.yaml
300-awskinesissource.yaml
300-awsperformanceinsightssource.yaml
300-awss3source.yaml
300-awssnssource.yaml
300-awssqssource.yaml
300-azureactivitylogssource.yaml
300-azureblobstoragesource.yaml
300-azureeventgridsource.yaml
300-azureeventhubsource.yaml
300-azureiothubsource.yaml
300-azurequeuestoragesource.yaml
300-azureservicebusqueuesource.yaml
300-googlecloudauditlogssource.yaml
300-googlecloudbillingsource.yaml
300-googlecloudpubsubsource.yaml
300-googlecloudrepositoriessource.yaml
300-googlecloudstoragesource.yaml
300-httppollersource.yaml
300-ocimetricssource.yaml
300-salesforcesource.yaml
300-slacksource.yaml
300-twiliosource.yaml
300-webhooksource.yaml
300-zendesksource.yaml

301-alibabaosstarget.yaml
301-awscomprehendtarget.yaml
301-awstargets.yaml
301-confluenttarget.yaml
301-datadogtarget.yaml
301-elasticsearchtarget.yaml
301-googlecloudstoragetarget.yaml
301-googlecloudworkflowstarget.yaml
301-googlefirestoretarget.yaml
301-googlesheettarget.yaml
301-hasuratarget.yaml
301-httptarget.yaml
301-infratarget.yaml
301-jiratarget.yaml
301-logztarget.yaml
301-oracletarget.yaml
301-salesforcetarget.yaml
301-sendgridtarget.yaml
301-slacktarget.yaml
301-splunktarget.yaml
301-tektontarget.yaml
301-twiliotarget.yaml
301-uipathtarget.yaml
301-zendesktarget.yaml

302-filter.yaml
302-splitter.yaml

303-function.yaml

304-transformation.yaml
```

### CODE REVIEW

**Review by JeffNeff — APPROVED** [review]
<3

**Comment by cab105** [comment]
Not too bad. Only issue I have is with the `301-awstargets.yaml`. Shouldn't it be `301-awstarget.yaml` to eensure it'll get caught shell globs against `*target.yaml`?

**Comment by antoineco** [comment]
@cab105 if we do this, let's split that huge file into individual CRDs then?

**Comment by cab105** [comment]
@antoineco Can do that as a first step since I know you've been wanting to split it up for a while.

**Review by cab105 — APPROVED** [review]

**Comment by antoineco** [comment]
Also true 😄

**Pull request merged**
