### PR TITLE
sample: fix googlecloudstoragesource.yaml sample

### PR DESCRIPTION
**Pull request by sameersbn**

### CODE REVIEW

**Review by sebgoa — APPROVED** [review]

**Comment by tzununbekov** [comment]
This is an invalid change, please do not merge 🙅‍♂️ 
https://github.com/triggermesh/triggermesh/blob/main/config/300-googlecloudstoragesource.yaml#L100

**Comment by sameersbn** [comment]
btw, with the 1.25 release `spec.auth.serviceAccountKey` is not accepted.

**Comment by tzununbekov** [comment]
> btw, with the 1.25 release `spec.auth.serviceAccountKey` is not accepted.

what do you mean by "not accepted"? It was [merged](https://github.com/triggermesh/triggermesh/commit/fcbc6e40caee9e8cd3094b9ff3e9e2f8d93f2e78) in February and released in 1.24.0:
https://docs.triggermesh.io/1.24/reference/sources/#sources.triggermesh.io/v1alpha1.GoogleCloudSourceAuth

**Comment by sameersbn** [comment]
> what do you mean by "not accepted"?

Oh sorry. I forgot I am running the Tanzu packaged version. It's the older release. My bad!

**Pull request closed without merging**
